### ISSUE TITLE
Change github About

### ISSUE THREAD

**Issue by AndreiCherniaev** [heavyC1oud/smilebrd#5]
1) I suggest to add [Теги](https://habr.com/ru/articles/552216/) based on habr to About (right upper corner).

2) To About's web site let's add https://habr.com/ru/articles/552216/

**Comment by heavyC1oud** [comment]
usually people come here from habr, not vice versa. withal link to habr article present in "additional description"

**Comment by AndreiCherniaev** [comment]
Anyway let's add tags and website because sometimes people search information not in Google directory but in GitHub...

**Comment by AndreiCherniaev** [comment]
Да давайте добавим!!!

**Comment by heavyC1oud** [comment]
no need to be annoying

**Comment by heavyC1oud** [comment]
I already said that you can create a fork and I will add a link to it in the article
